import { PrismaClient } from '@prisma/client';

export async function seedShipSkins(prisma: PrismaClient) {
  const shipSkins = [
    {
      name: "701",
      ovveride_materials: [],
      reference_ship: 701,
      class_filter: "Endymion",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 701,
      item_name: "Black Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_BlackFighter.T_Icon_Sk_BlackFighter'",
      description: ""
    },
    {
      name: "702",
      ovveride_materials: [],
      reference_ship: 702,
      class_filter: "Endymion",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 702,
      item_name: "Black Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_BlackCarrier.T_Icon_Sk_BlackCarrier'",
      description: ""
    },
    {
      name: "703",
      ovveride_materials: [],
      reference_ship: 703,
      class_filter: "Endymion",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 703,
      item_name: "Black Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_BlackHunter.T_Icon_Sk_BlackHunter'",
      description: ""
    },
    {
      name: "704",
      ovveride_materials: [],
      reference_ship: 704,
      class_filter: "Endymion",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 704,
      item_name: "Black Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_BlackFreighter.T_Icon_Sk_BlackFreighter'",
      description: ""
    },
    {
      name: "705",
      ovveride_materials: [],
      reference_ship: 705,
      class_filter: "Endymion",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 705,
      item_name: "Black Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_BlackAttacker.T_Icon_Sk_BlackAttacker'",
      description: ""
    },
    {
      name: "706",
      ovveride_materials: [],
      reference_ship: 706,
      class_filter: "Endymion",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 706,
      item_name: "Black Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_BlackDestroyer.T_Icon_Sk_BlackDestroyer'",
      description: ""
    },
    {
      name: "707",
      ovveride_materials: [],
      reference_ship: 707,
      class_filter: "Endymion",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 707,
      item_name: "Black Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_BlackBehemoth.T_Icon_Sk_BlackBehemoth'",
      description: ""
    },
    {
      name: "301",
      ovveride_materials: [],
      reference_ship: 301,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 301,
      item_name: "Colonies Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_ColoniesFighter.T_Icon_Sk_ColoniesFighter'",
      description: ""
    },
    {
      name: "302",
      ovveride_materials: [],
      reference_ship: 301,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 302,
      item_name: "Enclave Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_EnclaveFighter.T_Icon_Sk_EnclaveFighter'",
      description: ""
    },
    {
      name: "303",
      ovveride_materials: [],
      reference_ship: 302,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 303,
      item_name: "Colonies Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_ColoniesCarrier.T_Icon_Sk_ColoniesCarrier'",
      description: ""
    },
    {
      name: "304",
      ovveride_materials: [],
      reference_ship: 302,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 304,
      item_name: "Enclave Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_EnclaveCarrier.T_Icon_Sk_EnclaveCarrier'",
      description: ""
    },
    {
      name: "305",
      ovveride_materials: [],
      reference_ship: 303,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 305,
      item_name: "Colonies Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_ColoniesHunter.T_Icon_Sk_ColoniesHunter'",
      description: ""
    },
    {
      name: "306",
      ovveride_materials: [],
      reference_ship: 303,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 306,
      item_name: "Enclave Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_EnclaveHunter.T_Icon_Sk_EnclaveHunter'",
      description: ""
    },
    {
      name: "307",
      ovveride_materials: [],
      reference_ship: 304,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 307,
      item_name: "Colonies Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_ColoniesFreighter.T_Icon_Sk_ColoniesFreighter'",
      description: ""
    },
    {
      name: "308",
      ovveride_materials: [],
      reference_ship: 304,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 308,
      item_name: "Enclave Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_EnclaveFreighter.T_Icon_Sk_EnclaveFreighter'",
      description: ""
    },
    {
      name: "309",
      ovveride_materials: [],
      reference_ship: 305,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 309,
      item_name: "Colonies Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_ColoniesAttacker.T_Icon_Sk_ColoniesAttacker'",
      description: ""
    },
    {
      name: "310",
      ovveride_materials: [],
      reference_ship: 305,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 310,
      item_name: "Enclave Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_EnclaveAttacker.T_Icon_Sk_EnclaveAttacker'",
      description: ""
    },
    {
      name: "311",
      ovveride_materials: [],
      reference_ship: 306,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 311,
      item_name: "Colonie Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_ColoniesDestroyer.T_Icon_Sk_ColoniesDestroyer'",
      description: ""
    },
    {
      name: "312",
      ovveride_materials: [],
      reference_ship: 306,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 312,
      item_name: "Enclave Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_EnclaveDestroyer.T_Icon_Sk_EnclaveDestroyer'",
      description: ""
    },
    {
      name: "313",
      ovveride_materials: [],
      reference_ship: 307,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 313,
      item_name: "Colonie Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_ColoniesBehemoth.T_Icon_Sk_ColoniesBehemoth'",
      description: ""
    },
    {
      name: "314",
      ovveride_materials: [],
      reference_ship: 307,
      class_filter: "Nisus",
      cost_price: 1000,
      money_type: 1,
      static_mesh: "None",
      reference: 314,
      item_name: "Enclave Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/SkinsIcons/T_Icon_Sk_EnclaveBehemoth.T_Icon_Sk_EnclaveBehemoth'",
      description: ""
    }
  ];

  await prisma.shipSkins.createMany({
    data: shipSkins,
  });

  console.log('Ships seeded successfully');
}