import { PrismaClient } from '@prisma/client';

export async function seedShips(prisma: PrismaClient) {
  const ships = [
    {
      name: "101",
      size: 1,
      wings_size: 0,
      speed: 18,
      evasion: 40,
      cargo_space: 70,
      shield: 35,
      gun_slots: 16,
      missile_slots: 2,
      misc_slots: 8,
      ship_model: "Fighter",
      ship_class: "Zephyr",
      radar_range: 0,
      repair_per_hp: 0.43999999761581421,
      level_required: 0,
      total_hp: 400,
      cost_price: 35000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/01-Zephyr/SM_Ships_Zephyr_fighter.SM_Ships_Zephyr_fighter'",
      reference: 101,
      item_name: "Zephyr Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/01-Zephyr/T_Icon_ZepFighter.T_Icon_ZepFighter'",
      description: ""
    },
    {
      name: "102",
      size: 1.2999999523162842,
      wings_size: 0,
      speed: 10,
      evasion: 35,
      cargo_space: 600,
      shield: 45,
      gun_slots: 2,
      missile_slots: 1,
      misc_slots: 4,
      ship_model: "Carrier",
      ship_class: "Zephyr",
      radar_range: 0,
      repair_per_hp: 0.31000000238418579,
      level_required: 1,
      total_hp: 400,
      cost_price: 25000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/01-Zephyr/SM_Ships_Zephyr_carrier.SM_Ships_Zephyr_carrier'",
      reference: 102,
      item_name: "Zephyr Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/01-Zephyr/T_Icon_ZepCarrier.T_Icon_ZepCarrier'",
      description: ""
    },
    {
      name: "103",
      size: 1,
      wings_size: 0,
      speed: 14,
      evasion: 30,
      cargo_space: 80,
      shield: 40,
      gun_slots: 3,
      missile_slots: 3,
      misc_slots: 4,
      ship_model: "Hunter",
      ship_class: "Zephyr",
      radar_range: 0,
      repair_per_hp: 0.55000001192092896,
      level_required: 2,
      total_hp: 500,
      cost_price: 55000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/01-Zephyr/SM_Ships_Zephyr_hunter.SM_Ships_Zephyr_hunter'",
      reference: 103,
      item_name: "Zephyr Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/01-Zephyr/T_Icon_ZepHunter.T_Icon_ZepHunter'",
      description: ""
    },
    {
      name: "104",
      size: 0.69999998807907104,
      wings_size: 270,
      speed: 10,
      evasion: 20,
      cargo_space: 700,
      shield: 45,
      gun_slots: 6,
      missile_slots: 2,
      misc_slots: 5,
      ship_model: "Freighter",
      ship_class: "Zephyr",
      radar_range: 0,
      repair_per_hp: 0.82999998331069946,
      level_required: 3,
      total_hp: 600,
      cost_price: 100000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/01-Zephyr/SM_Ships_Zephyr_freighter.SM_Ships_Zephyr_freighter'",
      reference: 104,
      item_name: "Zephyr Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/01-Zephyr/T_Icon_ZepFreighter.T_Icon_ZepFreighter'",
      description: ""
    },
    {
      name: "105",
      size: 1.2000000476837158,
      wings_size: 0,
      speed: 14,
      evasion: 15,
      cargo_space: 90,
      shield: 50,
      gun_slots: 4,
      missile_slots: 4,
      misc_slots: 4,
      ship_model: "Attacker",
      ship_class: "Zephyr",
      radar_range: 0,
      repair_per_hp: 1.8600000143051147,
      level_required: 4,
      total_hp: 800,
      cost_price: 300000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/01-Zephyr/SM_Ships_Zephyr_attacker.SM_Ships_Zephyr_attacker'",
      reference: 105,
      item_name: "Zephyr Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/01-Zephyr/T_Icon_ZepAttacker.T_Icon_ZepAttacker'",
      description: ""
    },
    {
      name: "106",
      size: 0.80000001192092896,
      wings_size: 0,
      speed: 12,
      evasion: 10,
      cargo_space: 100,
      shield: 55,
      gun_slots: 5,
      missile_slots: 5,
      misc_slots: 5,
      ship_model: "Destroyer",
      ship_class: "Zephyr",
      radar_range: 0,
      repair_per_hp: 2.5,
      level_required: 5,
      total_hp: 1000,
      cost_price: 500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/01-Zephyr/SM_Ships_Zephyr_destroyer.SM_Ships_Zephyr_destroyer'",
      reference: 106,
      item_name: "Zephyr Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/01-Zephyr/T_Icon_ZepDestroyer.T_Icon_ZepDestroyer'",
      description: ""
    },
    {
      name: "107",
      size: 0.5,
      wings_size: 0,
      speed: 10,
      evasion: 13,
      cargo_space: 110,
      shield: 60,
      gun_slots: 9,
      missile_slots: 7,
      misc_slots: 6,
      ship_model: "Behemoth",
      ship_class: "Zephyr",
      radar_range: 0,
      repair_per_hp: 2.7799999713897705,
      level_required: 5,
      total_hp: 1800,
      cost_price: 1000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/01-Zephyr/SM_Ships_Zephyr_behemot.SM_Ships_Zephyr_behemot'",
      reference: 107,
      item_name: "Zephyr Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/01-Zephyr/T_Icon_ZepBehemoth.T_Icon_ZepBehemoth'",
      description: ""
    },
    {
      name: "201",
      size: 1,
      wings_size: 0,
      speed: 20,
      evasion: 45,
      cargo_space: 80,
      shield: 35,
      gun_slots: 3,
      missile_slots: 3,
      misc_slots: 3,
      ship_model: "Fighter",
      ship_class: "Arachne",
      radar_range: 0,
      repair_per_hp: 0.55000001192092896,
      level_required: 0,
      total_hp: 450,
      cost_price: 50000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/02-arachne/SM_ships_arachne_fighter.SM_ships_arachne_fighter'",
      reference: 201,
      item_name: "Arachne Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/02-Arachne/T_Icon_ArachFighter.T_Icon_ArachFighter'",
      description: ""
    },
    {
      name: "202",
      size: 0.40000000596046448,
      wings_size: 0,
      speed: 12,
      evasion: 40,
      cargo_space: 510,
      shield: 35,
      gun_slots: 2,
      missile_slots: 2,
      misc_slots: 4,
      ship_model: "Carrier",
      ship_class: "Arachne",
      radar_range: 0,
      repair_per_hp: 0.44999998807907104,
      level_required: 2,
      total_hp: 500,
      cost_price: 45000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/02-arachne/SM_ships_arachne_carrier.SM_ships_arachne_carrier'",
      reference: 202,
      item_name: "Arachne Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/02-Arachne/T_IconArachCarrier.T_IconArachCarrier'",
      description: ""
    },
    {
      name: "203",
      size: 1,
      wings_size: 0,
      speed: 16,
      evasion: 35,
      cargo_space: 90,
      shield: 40,
      gun_slots: 4,
      missile_slots: 4,
      misc_slots: 4,
      ship_model: "Hunter",
      ship_class: "Arachne",
      radar_range: 0,
      repair_per_hp: 0.43999999761581421,
      level_required: 2,
      total_hp: 800,
      cost_price: 70000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/02-arachne/SM_ships_arachne_hunter.SM_ships_arachne_hunter'",
      reference: 203,
      item_name: "Arachne Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/02-Arachne/T_Icon_ArachHunter.T_Icon_ArachHunter'",
      description: ""
    },
    {
      name: "204",
      size: 0.69999998807907104,
      wings_size: 0,
      speed: 12,
      evasion: 25,
      cargo_space: 650,
      shield: 40,
      gun_slots: 6,
      missile_slots: 3,
      misc_slots: 6,
      ship_model: "Freighter",
      ship_class: "Arachne",
      radar_range: 0,
      repair_per_hp: 0.76999998092651367,
      level_required: 4,
      total_hp: 900,
      cost_price: 140000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/02-arachne/SM_ships_arachne_freighter.SM_ships_arachne_freighter'",
      reference: 204,
      item_name: "Arachne Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/02-Arachne/T_Icon_ArachFreighter.T_Icon_ArachFreighter'",
      description: ""
    },
    {
      name: "205",
      size: 0.80000001192092896,
      wings_size: 0,
      speed: 16,
      evasion: 20,
      cargo_space: 100,
      shield: 45,
      gun_slots: 5,
      missile_slots: 6,
      misc_slots: 5,
      ship_model: "Attacker",
      ship_class: "Arachne",
      radar_range: 0,
      repair_per_hp: 1.75,
      level_required: 5,
      total_hp: 1000,
      cost_price: 350000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/02-arachne/SM_ships_arachne_attacker.SM_ships_arachne_attacker'",
      reference: 205,
      item_name: "Arachne Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/02-Arachne/T_Icon_ArachArracker.T_Icon_ArachArracker'",
      description: ""
    },
    {
      name: "206",
      size: 0.80000001192092896,
      wings_size: 0,
      speed: 14,
      evasion: 15,
      cargo_space: 110,
      shield: 50,
      gun_slots: 6,
      missile_slots: 5,
      misc_slots: 6,
      ship_model: "Destroyer",
      ship_class: "Arachne",
      radar_range: 0,
      repair_per_hp: 2.1600000858306885,
      level_required: 6,
      total_hp: 1500,
      cost_price: 650000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/02-arachne/SM_ships_arachne_destroyer.SM_ships_arachne_destroyer'",
      reference: 206,
      item_name: "Arachne Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/02-Arachne/T_Icon_ArachDestroyer.T_Icon_ArachDestroyer'",
      description: ""
    },
    {
      name: "207",
      size: 0.34999999403953552,
      wings_size: 0,
      speed: 10,
      evasion: 14,
      cargo_space: 130,
      shield: 55,
      gun_slots: 9,
      missile_slots: 8,
      misc_slots: 7,
      ship_model: "Behemoth",
      ship_class: "Arachne",
      radar_range: 0,
      repair_per_hp: 3,
      level_required: 6,
      total_hp: 2000,
      cost_price: 1200000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/02-arachne/SM_ships_arachne_behemoth.SM_ships_arachne_behemoth'",
      reference: 207,
      item_name: "Arachne Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/02-Arachne/T_Icon_ArachBehemoth.T_Icon_ArachBehemoth'",
      description: ""
    },
    {
      name: "301",
      size: 1,
      wings_size: 270,
      speed: 18,
      evasion: 45,
      cargo_space: 75,
      shield: 45,
      gun_slots: 4,
      missile_slots: 4,
      misc_slots: 3,
      ship_model: "Fighter",
      ship_class: "Nisus",
      radar_range: 0,
      repair_per_hp: 0.60000002384185791,
      level_required: 3,
      total_hp: 750,
      cost_price: 90000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/03-Nisus/SM_ships_Nisus_fighter.SM_ships_Nisus_fighter'",
      reference: 301,
      item_name: "Nisus Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/03-nisus/T_Icon_NisFighter.T_Icon_NisFighter'",
      description: ""
    },
    {
      name: "302",
      size: 0.10000000149011612,
      wings_size: 270,
      speed: 10,
      evasion: 40,
      cargo_space: 700,
      shield: 50,
      gun_slots: 3,
      missile_slots: 3,
      misc_slots: 4,
      ship_model: "Carrier",
      ship_class: "Nisus",
      radar_range: 0,
      repair_per_hp: 0.52999997138977051,
      level_required: 3,
      total_hp: 800,
      cost_price: 85000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/03-Nisus/SM_ships_Nisus_carrier.SM_ships_Nisus_carrier'",
      reference: 302,
      item_name: "Nisus Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/03-nisus/T_Icon_NisCarrier.T_Icon_NisCarrier'",
      description: ""
    },
    {
      name: "303",
      size: 1,
      wings_size: 270,
      speed: 14,
      evasion: 35,
      cargo_space: 85,
      shield: 55,
      gun_slots: 5,
      missile_slots: 5,
      misc_slots: 4,
      ship_model: "Hunter",
      ship_class: "Nisus",
      radar_range: 0,
      repair_per_hp: 0.72000002861022949,
      level_required: 4,
      total_hp: 1000,
      cost_price: 145000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/03-Nisus/SM_ships_Nisus_hunter.SM_ships_Nisus_hunter'",
      reference: 303,
      item_name: "Nisus Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/03-nisus/T_Icon_NisHunter.T_Icon_NisHunter'",
      description: ""
    },
    {
      name: "304",
      size: 0.15000000596046448,
      wings_size: 270,
      speed: 10,
      evasion: 25,
      cargo_space: 800,
      shield: 55,
      gun_slots: 6,
      missile_slots: 4,
      misc_slots: 5,
      ship_model: "Freighter",
      ship_class: "Nisus",
      radar_range: 0,
      repair_per_hp: 1.3600000143051147,
      level_required: 4,
      total_hp: 1100,
      cost_price: 300000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/03-Nisus/SM_ships_Nisus_freighter.SM_ships_Nisus_freighter'",
      reference: 304,
      item_name: "Nisus Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/03-nisus/T_Icon_NisFreighter.T_Icon_NisFreighter'",
      description: ""
    },
    {
      name: "305",
      size: 0.20000000298023224,
      wings_size: 270,
      speed: 14,
      evasion: 20,
      cargo_space: 95,
      shield: 58,
      gun_slots: 6,
      missile_slots: 7,
      misc_slots: 4,
      ship_model: "Attacker",
      ship_class: "Nisus",
      radar_range: 0,
      repair_per_hp: 1.5,
      level_required: 5,
      total_hp: 1500,
      cost_price: 450000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/03-Nisus/SM_ships_Nisus_attacker.SM_ships_Nisus_attacker'",
      reference: 305,
      item_name: "Nisus Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/03-nisus/T_Icon_NisAttacker.T_Icon_NisAttacker'",
      description: ""
    },
    {
      name: "306",
      size: 0.15000000596046448,
      wings_size: 270,
      speed: 12,
      evasion: 15,
      cargo_space: 105,
      shield: 58,
      gun_slots: 7,
      missile_slots: 8,
      misc_slots: 5,
      ship_model: "Destroyer",
      ship_class: "Nisus",
      radar_range: 0,
      repair_per_hp: 2.3599998950958252,
      level_required: 5,
      total_hp: 1800,
      cost_price: 850000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/03-Nisus/SM_ships_Nisus_destroyer.SM_ships_Nisus_destroyer'",
      reference: 306,
      item_name: "Nisus Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/03-nisus/T_Icon_NisFighter.T_Icon_NisFighter'",
      description: ""
    },
    {
      name: "307",
      size: 0.039999999105930328,
      wings_size: 270,
      speed: 8,
      evasion: 15,
      cargo_space: 115,
      shield: 62,
      gun_slots: 10,
      missile_slots: 12,
      misc_slots: 6,
      ship_model: "Behemoth",
      ship_class: "Nisus",
      radar_range: 0,
      repair_per_hp: 3.6400001049041748,
      level_required: 6,
      total_hp: 2200,
      cost_price: 1400000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/03-Nisus/SM_ships_Nisus_behemoth.SM_ships_Nisus_behemoth'",
      reference: 307,
      item_name: "Nisus Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/03-nisus/T_Icon_NisBehemoth.T_Icon_NisBehemoth'",
      description: ""
    },
    {
      name: "401",
      size: 1,
      wings_size: 0,
      speed: 18,
      evasion: 55,
      cargo_space: 80,
      shield: 40,
      gun_slots: 6,
      missile_slots: 2,
      misc_slots: 3,
      ship_model: "Fighter",
      ship_class: "Moros",
      radar_range: 0,
      repair_per_hp: 0.68999999761581421,
      level_required: 8,
      total_hp: 800,
      cost_price: 2000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/04-Moros/SM_ships_moros_fighter.SM_ships_moros_fighter'",
      reference: 401,
      item_name: "Moros Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/04-moros/T_7.T_7'",
      description: ""
    },
    {
      name: "402",
      size: 0.30000001192092896,
      wings_size: 0,
      speed: 10,
      evasion: 50,
      cargo_space: 800,
      shield: 45,
      gun_slots: 5,
      missile_slots: 2,
      misc_slots: 4,
      ship_model: "Carrier",
      ship_class: "Moros",
      radar_range: 0,
      repair_per_hp: 0.5,
      level_required: 9,
      total_hp: 1000,
      cost_price: 2200000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/04-Moros/SM_ships_moros_carrier.SM_ships_moros_carrier'",
      reference: 402,
      item_name: "Moros Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/04-moros/T_Icon_MorCarrier.T_Icon_MorCarrier'",
      description: ""
    },
    {
      name: "403",
      size: 0.80000001192092896,
      wings_size: 0,
      speed: 14,
      evasion: 45,
      cargo_space: 90,
      shield: 47,
      gun_slots: 7,
      missile_slots: 4,
      misc_slots: 4,
      ship_model: "Hunter",
      ship_class: "Moros",
      radar_range: 0,
      repair_per_hp: 1,
      level_required: 10,
      total_hp: 1000,
      cost_price: 3500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/04-Moros/SM_ships_moros_SM_ships_moros_hunter.SM_ships_moros_SM_ships_moros_hunter'",
      reference: 403,
      item_name: "Moros Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/04-moros/T_2.T_2'",
      description: ""
    },
    {
      name: "404",
      size: 0.5,
      wings_size: 0,
      speed: 10,
      evasion: 35,
      cargo_space: 750,
      shield: 50,
      gun_slots: 8,
      missile_slots: 4,
      misc_slots: 6,
      ship_model: "Freighter",
      ship_class: "Moros",
      radar_range: 0,
      repair_per_hp: 1.4600000381469727,
      level_required: 10,
      total_hp: 1200,
      cost_price: 7000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/04-Moros/SM_ships_moros_freighter.SM_ships_moros_freighter'",
      reference: 404,
      item_name: "Moros Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/04-moros/T_5.T_5'",
      description: ""
    },
    {
      name: "405",
      size: 0.20000000298023224,
      wings_size: 0,
      speed: 12,
      evasion: 30,
      cargo_space: 100,
      shield: 50,
      gun_slots: 8,
      missile_slots: 6,
      misc_slots: 6,
      ship_model: "Attacker",
      ship_class: "Moros",
      radar_range: 0,
      repair_per_hp: 2.3399999141693115,
      level_required: 11,
      total_hp: 1600,
      cost_price: 7500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/04-Moros/SM_ships_moros_attacker.SM_ships_moros_attacker'",
      reference: 405,
      item_name: "Moros Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/04-moros/T_4.T_4'",
      description: ""
    },
    {
      name: "406",
      size: 0.11999999731779099,
      wings_size: 0,
      speed: 10,
      evasion: 25,
      cargo_space: 110,
      shield: 55,
      gun_slots: 9,
      missile_slots: 9,
      misc_slots: 7,
      ship_model: "Destroyer",
      ship_class: "Moros",
      radar_range: 0,
      repair_per_hp: 3.9100000858306885,
      level_required: 13,
      total_hp: 2300,
      cost_price: 11500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/04-Moros/SM_ships_moros_destroyer.SM_ships_moros_destroyer'",
      reference: 406,
      item_name: "Moros Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/04-moros/T_3.T_3'",
      description: ""
    },
    {
      name: "407",
      size: 0.029999999329447746,
      wings_size: 0,
      speed: 8,
      evasion: 20,
      cargo_space: 130,
      shield: 57,
      gun_slots: 12,
      missile_slots: 11,
      misc_slots: 8,
      ship_model: "Behemoth",
      ship_class: "Moros",
      radar_range: 0,
      repair_per_hp: 9,
      level_required: 13,
      total_hp: 2500,
      cost_price: 15500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/04-Moros/SM_ships_moros_behemoth.SM_ships_moros_behemoth'",
      reference: 407,
      item_name: "Moros Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/04-moros/T_Icon_MorBehemoth.T_Icon_MorBehemoth'",
      description: ""
    },
    {
      name: "501",
      size: 1,
      wings_size: 180,
      speed: 16,
      evasion: 40,
      cargo_space: 90,
      shield: 50,
      gun_slots: 5,
      missile_slots: 3,
      misc_slots: 4,
      ship_model: "Fighter",
      ship_class: "Nereid",
      radar_range: 0,
      repair_per_hp: 0.64999997615814209,
      level_required: 9,
      total_hp: 1000,
      cost_price: 1850000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/05-Nereid/Legacy/SM_ships_Nereid_fighter.SM_ships_Nereid_fighter'",
      reference: 501,
      item_name: "Nerreid Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/05-Nereid/T_Icon_NerFighter.T_Icon_NerFighter'",
      description: ""
    },
    {
      name: "502",
      size: 0.40000000596046448,
      wings_size: 180,
      speed: 10,
      evasion: 40,
      cargo_space: 1050,
      shield: 52,
      gun_slots: 4,
      missile_slots: 3,
      misc_slots: 5,
      ship_model: "Carrier",
      ship_class: "Nereid",
      radar_range: 0,
      repair_per_hp: 0.62999999523162842,
      level_required: 10,
      total_hp: 1200,
      cost_price: 2000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/05-Nereid/Legacy/SM_ships_Nereid_carrier.SM_ships_Nereid_carrier'",
      reference: 502,
      item_name: "Nereid Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/05-Nereid/T_Icon_NerCarrier.T_Icon_NerCarrier'",
      description: ""
    },
    {
      name: "503",
      size: 0.80000001192092896,
      wings_size: 180,
      speed: 12,
      evasion: 35,
      cargo_space: 100,
      shield: 55,
      gun_slots: 6,
      missile_slots: 5,
      misc_slots: 5,
      ship_model: "Hunter",
      ship_class: "Nereid",
      radar_range: 0,
      repair_per_hp: 1.0399999618530273,
      level_required: 10,
      total_hp: 1200,
      cost_price: 3000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/05-Nereid/Legacy/SM_ships_Nereid_hunter.SM_ships_Nereid_hunter'",
      reference: 503,
      item_name: "Nereid Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/05-Nereid/T_Icon_NerHunter.T_Icon_NerHunter'",
      description: ""
    },
    {
      name: "504",
      size: 0.40000000596046448,
      wings_size: 180,
      speed: 10,
      evasion: 25,
      cargo_space: 950,
      shield: 52,
      gun_slots: 7,
      missile_slots: 6,
      misc_slots: 7,
      ship_model: "Freighter",
      ship_class: "Nereid",
      radar_range: 0,
      repair_per_hp: 1.6100000143051147,
      level_required: 12,
      total_hp: 1400,
      cost_price: 8000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/05-Nereid/Legacy/SM_ships_Nereid_freighter.SM_ships_Nereid_freighter'",
      reference: 504,
      item_name: "Nereid Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/05-Nereid/T_Icon_NerFreighter.T_Icon_NerFreighter'",
      description: ""
    },
    {
      name: "505",
      size: 0.30000001192092896,
      wings_size: 180,
      speed: 10,
      evasion: 20,
      cargo_space: 350,
      shield: 57,
      gun_slots: 7,
      missile_slots: 7,
      misc_slots: 7,
      ship_model: "Attacker",
      ship_class: "Nereid",
      radar_range: 0,
      repair_per_hp: 2.7799999713897705,
      level_required: 12,
      total_hp: 1800,
      cost_price: 7000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/05-Nereid/Legacy/SM_ships_Nereid_attacker.SM_ships_Nereid_attacker'",
      reference: 505,
      item_name: "Nereid Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/05-Nereid/T_Icon_NerAttacker.T_Icon_NerAttacker'",
      description: ""
    },
    {
      name: "506",
      size: 0.30000001192092896,
      wings_size: 180,
      speed: 8,
      evasion: 15,
      cargo_space: 110,
      shield: 57,
      gun_slots: 8,
      missile_slots: 10,
      misc_slots: 7,
      ship_model: "Destroyer",
      ship_class: "Nereid",
      radar_range: 0,
      repair_per_hp: 11,
      level_required: 13,
      total_hp: 2500,
      cost_price: 10000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/05-Nereid/Legacy/SM_ships_Nereid_destroyer.SM_ships_Nereid_destroyer'",
      reference: 506,
      item_name: "Nereid Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/05-Nereid/T_Icon_NerDestroyer.T_Icon_NerDestroyer'",
      description: ""
    },
    {
      name: "507",
      size: 0.15000000596046448,
      wings_size: 180,
      speed: 6,
      evasion: 10,
      cargo_space: 170,
      shield: 62,
      gun_slots: 12,
      missile_slots: 12,
      misc_slots: 8,
      ship_model: "Behemoth",
      ship_class: "Nereid",
      radar_range: 0,
      repair_per_hp: 19.229999542236328,
      level_required: 13,
      total_hp: 2600,
      cost_price: 14000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/05-Nereid/Legacy/SM_ships_Nereid_behemot.SM_ships_Nereid_behemot'",
      reference: 507,
      item_name: "Nereid Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/05-Nereid/T_Icon_NerBehemoth.T_Icon_NerBehemoth'",
      description: ""
    },
    {
      name: "601",
      size: 1,
      wings_size: 0,
      speed: 14,
      evasion: 30,
      cargo_space: 70,
      shield: 47,
      gun_slots: 6,
      missile_slots: 5,
      misc_slots: 5,
      ship_model: "Fighter",
      ship_class: "Talos",
      radar_range: 0,
      repair_per_hp: 1.0499999523162842,
      level_required: 8,
      total_hp: 1100,
      cost_price: 2900000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/06-Talos/SM_ships_Talos_RedBite_fighter.SM_ships_Talos_RedBite_fighter'",
      reference: 601,
      item_name: "Talos Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/06-Talos/T_IconTalFighter.T_IconTalFighter'",
      description: ""
    },
    {
      name: "602",
      size: 0.5,
      wings_size: 0,
      speed: 8,
      evasion: 30,
      cargo_space: 900,
      shield: 50,
      gun_slots: 4,
      missile_slots: 5,
      misc_slots: 5,
      ship_model: "Carrier",
      ship_class: "Talos",
      radar_range: 0,
      repair_per_hp: 0.69999998807907104,
      level_required: 10,
      total_hp: 1350,
      cost_price: 3000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/06-Talos/SM_ships_Talos_RedBite_carrier.SM_ships_Talos_RedBite_carrier'",
      reference: 602,
      item_name: "Talos Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/06-Talos/T_IconTalCarrier.T_IconTalCarrier'",
      description: ""
    },
    {
      name: "603",
      size: 1,
      wings_size: 0,
      speed: 10,
      evasion: 30,
      cargo_space: 80,
      shield: 47,
      gun_slots: 8,
      missile_slots: 7,
      misc_slots: 6,
      ship_model: "Hunter",
      ship_class: "Talos",
      radar_range: 0,
      repair_per_hp: 1.7300000190734863,
      level_required: 11,
      total_hp: 1300,
      cost_price: 4500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/06-Talos/SM_ships_Talos_RedBite_hunter.SM_ships_Talos_RedBite_hunter'",
      reference: 603,
      item_name: "Talos Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/06-Talos/T_IconTalHunter.T_IconTalHunter'",
      description: ""
    },
    {
      name: "604",
      size: 0.89999997615814209,
      wings_size: 0,
      speed: 4,
      evasion: 20,
      cargo_space: 800,
      shield: 50,
      gun_slots: 8,
      missile_slots: 8,
      misc_slots: 7,
      ship_model: "Freighter",
      ship_class: "Talos",
      radar_range: 0,
      repair_per_hp: 3.0399999618530273,
      level_required: 12,
      total_hp: 1400,
      cost_price: 8500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/06-Talos/SM_ships_Talos_RedBite_freighter.SM_ships_Talos_RedBite_freighter'",
      reference: 604,
      item_name: "Talos Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/06-Talos/T_IconTalFreighter.T_IconTalFreighter'",
      description: ""
    },
    {
      name: "605",
      size: 0.30000001192092896,
      wings_size: 0,
      speed: 8,
      evasion: 15,
      cargo_space: 90,
      shield: 55,
      gun_slots: 9,
      missile_slots: 7,
      misc_slots: 8,
      ship_model: "Attacker",
      ship_class: "Talos",
      radar_range: 0,
      repair_per_hp: 12.5,
      level_required: 12,
      total_hp: 2000,
      cost_price: 8000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/06-Talos/SM_ships_Talos_RedBite_attacker.SM_ships_Talos_RedBite_attacker'",
      reference: 605,
      item_name: "Talos Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/06-Talos/T_IconTalAttacker.T_IconTalAttacker'",
      description: ""
    },
    {
      name: "606",
      size: 0.30000001192092896,
      wings_size: 0,
      speed: 6,
      evasion: 10,
      cargo_space: 100,
      shield: 55,
      gun_slots: 10,
      missile_slots: 10,
      misc_slots: 8,
      ship_model: "Destroyer",
      ship_class: "Talos",
      radar_range: 0,
      repair_per_hp: 27.030000686645508,
      level_required: 13,
      total_hp: 2600,
      cost_price: 12000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/06-Talos/SM_ships_Talos_RedBite_destroyer.SM_ships_Talos_RedBite_destroyer'",
      reference: 606,
      item_name: "Talos Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/06-Talos/T_IconTalDestroyer.T_IconTalDestroyer'",
      description: ""
    },
    {
      name: "607",
      size: 0.5,
      wings_size: 0,
      speed: 10,
      evasion: 10,
      cargo_space: 150,
      shield: 50,
      gun_slots: 12,
      missile_slots: 12,
      misc_slots: 6,
      ship_model: "Behemoth",
      ship_class: "Talos",
      radar_range: 0,
      repair_per_hp: 28.569999694824219,
      level_required: 14,
      total_hp: 2800,
      cost_price: 16000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/06-Talos/SM_ships_Talos_RedBite_behemoth.SM_ships_Talos_RedBite_behemoth'",
      reference: 607,
      item_name: "Talos Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/06-Talos/T_IconTalBehemoth.T_IconTalBehemoth'",
      description: ""
    },
    {
      name: "701",
      size: 1,
      wings_size: 270,
      speed: 14,
      evasion: 45,
      cargo_space: 190,
      shield: 40,
      gun_slots: 8,
      missile_slots: 6,
      misc_slots: 5,
      ship_model: "Fighter",
      ship_class: "Endymion",
      radar_range: 0,
      repair_per_hp: 0.34000000357627869,
      level_required: 13,
      total_hp: 1600,
      cost_price: 4500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/07-Endymion/whiteknight/SM_ships_EndymionWhite_fighter.SM_ships_EndymionWhite_fighter'",
      reference: 701,
      item_name: "Endynion Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/07-Endymion/T_Icon_EndyFighter.T_Icon_EndyFighter'",
      description: ""
    },
    {
      name: "702",
      size: 0.5,
      wings_size: 270,
      speed: 8,
      evasion: 30,
      cargo_space: 1200,
      shield: 40,
      gun_slots: 6,
      missile_slots: 4,
      misc_slots: 4,
      ship_model: "Carrier",
      ship_class: "Endymion",
      radar_range: 0,
      repair_per_hp: 5.8299999237060547,
      level_required: 14,
      total_hp: 1800,
      cost_price: 6500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/07-Endymion/whiteknight/SM_ships_EndymionWhite_carrier.SM_ships_EndymionWhite_carrier'",
      reference: 702,
      item_name: "Endymion Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/07-Endymion/T_Icon_EndyCarrier.T_Icon_EndyCarrier'",
      description: ""
    },
    {
      name: "703",
      size: 1,
      wings_size: 270,
      speed: 10,
      evasion: 35,
      cargo_space: 200,
      shield: 45,
      gun_slots: 9,
      missile_slots: 6,
      misc_slots: 5,
      ship_model: "Hunter",
      ship_class: "Endymion",
      radar_range: 0,
      repair_per_hp: 11.420000076293945,
      level_required: 14,
      total_hp: 1750,
      cost_price: 10000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/07-Endymion/whiteknight/SM_ships_EndymionWhite_hunter.SM_ships_EndymionWhite_hunter'",
      reference: 703,
      item_name: "Endymion Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/07-Endymion/T_Icon_EndyHunter.T_Icon_EndyHunter'",
      description: ""
    },
    {
      name: "704",
      size: 0.5,
      wings_size: 270,
      speed: 6,
      evasion: 25,
      cargo_space: 1100,
      shield: 50,
      gun_slots: 10,
      missile_slots: 8,
      misc_slots: 6,
      ship_model: "Freighter",
      ship_class: "Endymion",
      radar_range: 0,
      repair_per_hp: 13.75,
      level_required: 15,
      total_hp: 2000,
      cost_price: 13000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/07-Endymion/whiteknight/SM_ships_EndymionWhite_freighter.SM_ships_EndymionWhite_freighter'",
      reference: 704,
      item_name: "Endymion Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/07-Endymion/T_Icon_EndyFreighter.T_Icon_EndyFreighter'",
      description: ""
    },
    {
      name: "705",
      size: 0.30000001192092896,
      wings_size: 270,
      speed: 10,
      evasion: 30,
      cargo_space: 230,
      shield: 50,
      gun_slots: 10,
      missile_slots: 8,
      misc_slots: 6,
      ship_model: "Attacker",
      ship_class: "Endymion",
      radar_range: 0,
      repair_per_hp: 21.870000839233398,
      level_required: 15,
      total_hp: 2400,
      cost_price: 16000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/07-Endymion/whiteknight/SM_ships_EndymionWhite_Attacker.SM_ships_EndymionWhite_Attacker'",
      reference: 705,
      item_name: "Endymion Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/07-Endymion/T_Icon_EndyAttacker.T_Icon_EndyAttacker'",
      description: ""
    },
    {
      name: "706",
      size: 0.30000001192092896,
      wings_size: 270,
      speed: 8,
      evasion: 25,
      cargo_space: 210,
      shield: 55,
      gun_slots: 12,
      missile_slots: 10,
      misc_slots: 6,
      ship_model: "Destroyer",
      ship_class: "Endymion",
      radar_range: 0,
      repair_per_hp: 30,
      level_required: 16,
      total_hp: 3000,
      cost_price: 26000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/07-Endymion/whiteknight/SM_ships_EndymionWhite_destroyer.SM_ships_EndymionWhite_destroyer'",
      reference: 706,
      item_name: "Endymion Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/07-Endymion/T_Icon_EndyDestroyer.T_Icon_EndyDestroyer'",
      description: ""
    },
    {
      name: "707",
      size: 0.059999998658895493,
      wings_size: 270,
      speed: 3,
      evasion: 25,
      cargo_space: 230,
      shield: 60,
      gun_slots: 16,
      missile_slots: 12,
      misc_slots: 7,
      ship_model: "Behemoth",
      ship_class: "Endymion",
      radar_range: 0,
      repair_per_hp: 35.290000915527344,
      level_required: 17,
      total_hp: 3400,
      cost_price: 32000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/07-Endymion/whiteknight/SM_ships_EndymionWhite_behemoth.SM_ships_EndymionWhite_behemoth'",
      reference: 707,
      item_name: "Endymion Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/07-Endymion/T_Icon_EndyBehemoth.T_Icon_EndyBehemoth'",
      description: ""
    },
    {
      name: "801",
      size: 1,
      wings_size: 270,
      speed: 18,
      evasion: 35,
      cargo_space: 150,
      shield: 30,
      gun_slots: 8,
      missile_slots: 6,
      misc_slots: 5,
      ship_model: "Fighter",
      ship_class: "Hyperion",
      radar_range: 0,
      repair_per_hp: 7.3499999046325684,
      level_required: 14,
      total_hp: 1700,
      cost_price: 4000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/08-Hyperion/SM_shps_Hyperion_darkstorm_fighter.SM_shps_Hyperion_darkstorm_fighter'",
      reference: 801,
      item_name: "Hyperion Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/08-Hyperion/T_1.T_1'",
      description: ""
    },
    {
      name: "802",
      size: 0.30000001192092896,
      wings_size: 270,
      speed: 12,
      evasion: 25,
      cargo_space: 1300,
      shield: 40,
      gun_slots: 6,
      missile_slots: 4,
      misc_slots: 4,
      ship_model: "Carrier",
      ship_class: "Hyperion",
      radar_range: 0,
      repair_per_hp: 9.4600000381469727,
      level_required: 15,
      total_hp: 1850,
      cost_price: 7000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/08-Hyperion/SM_shps_Hyperion_darkstorm_carrier.SM_shps_Hyperion_darkstorm_carrier'",
      reference: 802,
      item_name: "Hyperion Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/08-Hyperion/T_2.T_2'",
      description: ""
    },
    {
      name: "803",
      size: 1,
      wings_size: 270,
      speed: 14,
      evasion: 30,
      cargo_space: 250,
      shield: 45,
      gun_slots: 9,
      missile_slots: 6,
      misc_slots: 5,
      ship_model: "Hunter",
      ship_class: "Hyperion",
      radar_range: 0,
      repair_per_hp: 10.529999732971191,
      level_required: 15,
      total_hp: 1900,
      cost_price: 8500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/08-Hyperion/SM_shps_Hyperion_darkstorm_hunter.SM_shps_Hyperion_darkstorm_hunter'",
      reference: 803,
      item_name: "Hyperion Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/08-Hyperion/T_3.T_3'",
      description: ""
    },
    {
      name: "804",
      size: 0.34999999403953552,
      wings_size: 270,
      speed: 10,
      evasion: 20,
      cargo_space: 1200,
      shield: 50,
      gun_slots: 10,
      missile_slots: 8,
      misc_slots: 5,
      ship_model: "Freighter",
      ship_class: "Hyperion",
      radar_range: 0,
      repair_per_hp: 15.899999618530273,
      level_required: 16,
      total_hp: 2200,
      cost_price: 12000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/08-Hyperion/SM_shps_Hyperion_darkstorm_freighter.SM_shps_Hyperion_darkstorm_freighter'",
      reference: 804,
      item_name: "Hyperion Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/08-Hyperion/T_4.T_4'",
      description: ""
    },
    {
      name: "805",
      size: 0.15999999642372131,
      wings_size: 270,
      speed: 14,
      evasion: 20,
      cargo_space: 400,
      shield: 50,
      gun_slots: 10,
      missile_slots: 8,
      misc_slots: 6,
      ship_model: "Attacker",
      ship_class: "Hyperion",
      radar_range: 0,
      repair_per_hp: 22,
      level_required: 16,
      total_hp: 2500,
      cost_price: 19000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/08-Hyperion/SM_shps_Hyperion_darkstorm_attacker.SM_shps_Hyperion_darkstorm_attacker'",
      reference: 805,
      item_name: "Hyperion Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/08-Hyperion/T_5.T_5'",
      description: ""
    },
    {
      name: "806",
      size: 0.11999999731779099,
      wings_size: 270,
      speed: 12,
      evasion: 20,
      cargo_space: 220,
      shield: 55,
      gun_slots: 12,
      missile_slots: 10,
      misc_slots: 6,
      ship_model: "Destroyer",
      ship_class: "Hyperion",
      radar_range: 0,
      repair_per_hp: 36.360000610351563,
      level_required: 16,
      total_hp: 2750,
      cost_price: 23000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/08-Hyperion/SM_shps_Hyperion_darkstorm_destroyer.SM_shps_Hyperion_darkstorm_destroyer'",
      reference: 806,
      item_name: "Hyperion Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/08-Hyperion/T_6.T_6'",
      description: ""
    },
    {
      name: "807",
      size: 0.05000000074505806,
      wings_size: 270,
      speed: 5,
      evasion: 25,
      cargo_space: 300,
      shield: 60,
      gun_slots: 14,
      missile_slots: 12,
      misc_slots: 7,
      ship_model: "Behemoth",
      ship_class: "Hyperion",
      radar_range: 0,
      repair_per_hp: 50,
      level_required: 17,
      total_hp: 2800,
      cost_price: 30000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/08-Hyperion/SM_shps_Hyperion_darkstorm_behemoth.SM_shps_Hyperion_darkstorm_behemoth'",
      reference: 807,
      item_name: "Hyperion Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/08-Hyperion/T_Icon_HypBehemoth.T_Icon_HypBehemoth'",
      description: ""
    },
    {
      name: "901",
      size: 1,
      wings_size: 90,
      speed: 15,
      evasion: 30,
      cargo_space: 90,
      shield: 35,
      gun_slots: 8,
      missile_slots: 6,
      misc_slots: 5,
      ship_model: "Fighter",
      ship_class: "Helios",
      radar_range: 0,
      repair_per_hp: 9.7200002670288086,
      level_required: 14,
      total_hp: 1850,
      cost_price: 5600000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/09-Helios/SM_Helios_Legacy_fighter.SM_Helios_Legacy_fighter'",
      reference: 901,
      item_name: "Helios Fighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/09-helios/T_Icon_HelFighter.T_Icon_HelFighter'",
      description: ""
    },
    {
      name: "902",
      size: 0.20000000298023224,
      wings_size: 90,
      speed: 10,
      evasion: 20,
      cargo_space: 1100,
      shield: 35,
      gun_slots: 6,
      missile_slots: 4,
      misc_slots: 4,
      ship_model: "Carrier",
      ship_class: "Helios",
      radar_range: 0,
      repair_per_hp: 14.75,
      level_required: 16,
      total_hp: 2000,
      cost_price: 7500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/09-Helios/SM_Helios_Legacy_carrier.SM_Helios_Legacy_carrier'",
      reference: 902,
      item_name: "Helios Carrier",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/09-helios/T_Icon_HelCarrier.T_Icon_HelCarrier'",
      description: ""
    },
    {
      name: "903",
      size: 0.80000001192092896,
      wings_size: 90,
      speed: 12,
      evasion: 25,
      cargo_space: 100,
      shield: 35,
      gun_slots: 9,
      missile_slots: 6,
      misc_slots: 5,
      ship_model: "Hunter",
      ship_class: "Helios",
      radar_range: 0,
      repair_per_hp: 15,
      level_required: 16,
      total_hp: 2200,
      cost_price: 11000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/09-Helios/SM_Helios_Legacy_hunter.SM_Helios_Legacy_hunter'",
      reference: 903,
      item_name: "Helios Hunter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/09-helios/T_Icon_HelHunter.T_Icon_HelHunter'",
      description: ""
    },
    {
      name: "904",
      size: 0.20000000298023224,
      wings_size: 90,
      speed: 8,
      evasion: 25,
      cargo_space: 1000,
      shield: 45,
      gun_slots: 10,
      missile_slots: 4,
      misc_slots: 5,
      ship_model: "Freighter",
      ship_class: "Helios",
      radar_range: 0,
      repair_per_hp: 17.700000762939453,
      level_required: 16,
      total_hp: 2400,
      cost_price: 14500000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/09-Helios/SM_Helios_Legacy_freighter.SM_Helios_Legacy_freighter'",
      reference: 904,
      item_name: "Helios Freighter",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/09-helios/T_Icon_HelFreighter.T_Icon_HelFreighter'",
      description: ""
    },
    {
      name: "905",
      size: 0.20000000298023224,
      wings_size: 90,
      speed: 10,
      evasion: 20,
      cargo_space: 130,
      shield: 45,
      gun_slots: 10,
      missile_slots: 8,
      misc_slots: 6,
      ship_model: "Attacker",
      ship_class: "Helios",
      radar_range: 0,
      repair_per_hp: 22.319999694824219,
      level_required: 16,
      total_hp: 2800,
      cost_price: 19000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/09-Helios/SM_Helios_Legacy_attacker.SM_Helios_Legacy_attacker'",
      reference: 905,
      item_name: "Helios Attacker",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/09-helios/T_Icon_HelAttacker.T_Icon_HelAttacker'",
      description: ""
    },
    {
      name: "906",
      size: 0.20000000298023224,
      wings_size: 90,
      speed: 10,
      evasion: 25,
      cargo_space: 110,
      shield: 50,
      gun_slots: 12,
      missile_slots: 10,
      misc_slots: 6,
      ship_model: "Destroyer",
      ship_class: "Helios",
      radar_range: 0,
      repair_per_hp: 40.900001525878906,
      level_required: 17,
      total_hp: 3300,
      cost_price: 27000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/09-Helios/SM_Helios_Legacy_destroyer.SM_Helios_Legacy_destroyer'",
      reference: 906,
      item_name: "Helios Destroyer",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/09-helios/T_Icon_HelDestroyer.T_Icon_HelDestroyer'",
      description: ""
    },
    {
      name: "907",
      size: 0.10000000149011612,
      wings_size: 90,
      speed: 4,
      evasion: 20,
      cargo_space: 250,
      shield: 60,
      gun_slots: 16,
      missile_slots: 12,
      misc_slots: 7,
      ship_model: "Behemoth",
      ship_class: "Helios",
      radar_range: 0,
      repair_per_hp: 47.939998626708984,
      level_required: 18,
      total_hp: 3650,
      cost_price: 35000000,
      money_type: 0,
      static_mesh: "StaticMesh'/Game/Assets/ShipSpace/09-Helios/SM_Helios_Legacy_behemoth.SM_Helios_Legacy_behemoth'",
      reference: 907,
      item_name: "Helios Behemoth",
      icon: "Texture2D'/Game/Assets/Hangar/ShipsIcons/09-helios/T_Icon_HelBehemoth.T_Icon_HelBehemoth'",
      description: ""
    }
  ];

  await prisma.ships.createMany({
    data: ships,
  });

  console.log('Ships seeded successfully');
}