import { PrismaClient } from '@prisma/client';

export async function seedGuns(prisma: PrismaClient) {
  const guns = [
    {
      name: "101",
      firing_sound: "None",
      accuracy: 50,
      speed: 75,
      damage: 4,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_PLSBeam.BP_Gun_PLSBeam_C'",
      repair_per_hp: 0.33000001311302185,
      level_required: 0,
      total_hp: 150,
      cost_price: 2500,
      money_type: 0,
      static_mesh: "None",
      reference: 101,
      item_name: "PLS Beam",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_PLS_Beam.T_Icon_PLS_Beam'",
      description: ""
    },
    {
      name: "102",
      firing_sound: "None",
      accuracy: 45,
      speed: 80,
      damage: 6,
      type: 2,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_RPDBeam.BP_Gun_RPDBeam_C'",
      repair_per_hp: 0.20000000298023224,
      level_required: 0,
      total_hp: 200,
      cost_price: 5000,
      money_type: 0,
      static_mesh: "None",
      reference: 102,
      item_name: "RPD Beam",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_RPD_Beam.T_Icon_RPD_Beam'",
      description: ""
    },
    {
      name: "103",
      firing_sound: "None",
      accuracy: 65,
      speed: 65,
      damage: 10,
      type: 1,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_V1Blaster.BP_Gun_V1Blaster_C'",
      repair_per_hp: 2.5,
      level_required: 0,
      total_hp: 100,
      cost_price: 7500,
      money_type: 0,
      static_mesh: "None",
      reference: 103,
      item_name: "V1 Blaster",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_V1_Blaster.T_Icon_V1_Blaster'",
      description: ""
    },
    {
      name: "104",
      firing_sound: "None",
      accuracy: 60,
      speed: 75,
      damage: 10,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_Mk1Fury.BP_Gun_Mk1Fury_C'",
      repair_per_hp: 0.67000001668930054,
      level_required: 0,
      total_hp: 150,
      cost_price: 15000,
      money_type: 0,
      static_mesh: "None",
      reference: 104,
      item_name: "Mk1 Fury",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Mk1_Fury.T_Icon_Mk1_Fury'",
      description: ""
    },
    {
      name: "105",
      firing_sound: "None",
      accuracy: 55,
      speed: 65,
      damage: 14,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_IonStream.BP_Gun_IonStream_C'",
      repair_per_hp: 0.36000001430511475,
      level_required: 0,
      total_hp: 250,
      cost_price: 24000,
      money_type: 0,
      static_mesh: "None",
      reference: 105,
      item_name: "Ion Stream",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Ion_Stream.T_Icon_Ion_Stream'",
      description: ""
    },
    {
      name: "106",
      firing_sound: "None",
      accuracy: 65,
      speed: 65,
      damage: 16,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_DriveWarper.BP_Gun_DriveWarper_C'",
      repair_per_hp: 2,
      level_required: 0,
      total_hp: 150,
      cost_price: 27500,
      money_type: 0,
      static_mesh: "None",
      reference: 106,
      item_name: "Drive Warper",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Drive_Warper.T_Icon_Drive_Warper'",
      description: ""
    },
    {
      name: "107",
      firing_sound: "None",
      accuracy: 35,
      speed: 90,
      damage: 12,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_k7.BP_Gun_k7_C'",
      repair_per_hp: 0.20000000298023224,
      level_required: 0,
      total_hp: 500,
      cost_price: 17500,
      money_type: 0,
      static_mesh: "None",
      reference: 107,
      item_name: "K7 Cannon",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_K7_Cannon.T_Icon_K7_Cannon'",
      description: ""
    },
    {
      name: "108",
      firing_sound: "None",
      accuracy: 75,
      speed: 50,
      damage: 23,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_Mk1Sunburst.BP_Gun_Mk1Sunburst_C'",
      repair_per_hp: 7.3299999237060547,
      level_required: 0,
      total_hp: 150,
      cost_price: 40000,
      money_type: 0,
      static_mesh: "None",
      reference: 108,
      item_name: "Mk1 Sunburst",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Mk1_Sunburst.T_Icon_Mk1_Sunburst'",
      description: ""
    },
    {
      name: "109",
      firing_sound: "None",
      accuracy: 55,
      speed: 75,
      damage: 16,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_Mk2Fury.BP_Gun_Mk2Fury_C'",
      repair_per_hp: 3.25,
      level_required: 0,
      total_hp: 200,
      cost_price: 45000,
      money_type: 0,
      static_mesh: "None",
      reference: 109,
      item_name: "Mk2 Fury",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Mk2_Fury.T_Icon_Mk2_Fury'",
      description: ""
    },
    {
      name: "110",
      firing_sound: "None",
      accuracy: 70,
      speed: 70,
      damage: 18,
      type: 1,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_V2Blaster.BP_Gun_V2Blaster_C'",
      repair_per_hp: 2.5,
      level_required: 0,
      total_hp: 200,
      cost_price: 32500,
      money_type: 0,
      static_mesh: "None",
      reference: 110,
      item_name: "V2 Blaster",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_V2_Blaster.T_Icon_V2_Blaster'",
      description: ""
    },
    {
      name: "111",
      firing_sound: "None",
      accuracy: 40,
      speed: 90,
      damage: 14,
      type: 1,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_k14.BP_Gun_k14_C'",
      repair_per_hp: 0.36000001430511475,
      level_required: 0,
      total_hp: 550,
      cost_price: 24000,
      money_type: 0,
      static_mesh: "None",
      reference: 111,
      item_name: "K14 Cannon",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_K14_Cannon.T_Icon_K14_Cannon'",
      description: ""
    },
    {
      name: "112",
      firing_sound: "None",
      accuracy: 45,
      speed: 90,
      damage: 14,
      type: 1,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_k14s.BP_Gun_k14s_C'",
      repair_per_hp: 2.0799999237060547,
      level_required: 0,
      total_hp: 600,
      cost_price: 52500,
      money_type: 0,
      static_mesh: "None",
      reference: 112,
      item_name: "K14S Cannon",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_K14S_Cannon.T_Icon_K14S_Cannon'",
      description: ""
    },
    {
      name: "113",
      firing_sound: "None",
      accuracy: 65,
      speed: 60,
      damage: 23,
      type: 2,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_RazorRay.BP_Gun_RazorRay_C'",
      repair_per_hp: 6,
      level_required: 0,
      total_hp: 350,
      cost_price: 60000,
      money_type: 0,
      static_mesh: "None",
      reference: 113,
      item_name: "Razor Ray",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Razor_Ray.T_Icon_Razor_Ray'",
      description: ""
    },
    {
      name: "114",
      firing_sound: "None",
      accuracy: 60,
      speed: 75,
      damage: 20,
      type: 2,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_LanceRay.BP_Gun_LanceRay_C'",
      repair_per_hp: 5.3299999237060547,
      level_required: 0,
      total_hp: 150,
      cost_price: 35000,
      money_type: 0,
      static_mesh: "None",
      reference: 114,
      item_name: "Lance Ray",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Lance_Ray.T_Icon_Lance_Ray'",
      description: ""
    },
    {
      name: "115",
      firing_sound: "None",
      accuracy: 75,
      speed: 60,
      damage: 26,
      type: 1,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_Mk2Sunburst.BP_Gun_Mk2Sunburst_C'",
      repair_per_hp: 6.5,
      level_required: 0,
      total_hp: 450,
      cost_price: 87500,
      money_type: 0,
      static_mesh: "None",
      reference: 115,
      item_name: "Mk2 Sunburst",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Mk2_Sunburst.T_Icon_Mk2_Sunburst'",
      description: ""
    },
    {
      name: "116",
      firing_sound: "None",
      accuracy: 55,
      speed: 70,
      damage: 25,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_Mk3Fury.BP_Gun_Mk3Fury_C'",
      repair_per_hp: 5,
      level_required: 0,
      total_hp: 350,
      cost_price: 65000,
      money_type: 0,
      static_mesh: "None",
      reference: 116,
      item_name: "Mk3 Fury",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Mk3_Fury.T_Icon_Mk3_Fury'",
      description: ""
    },
    {
      name: "117",
      firing_sound: "None",
      accuracy: 40,
      speed: 70,
      damage: 28,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_SilverStorm1.BP_Gun_SilverStorm1_C'",
      repair_per_hp: 60,
      level_required: 0,
      total_hp: 250,
      cost_price: 55000,
      money_type: 0,
      static_mesh: "None",
      reference: 117,
      item_name: "Silver Storm l",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Silver_Storm_l.T_Icon_Silver_Storm_l'",
      description: ""
    },
    {
      name: "118",
      firing_sound: "None",
      accuracy: 60,
      speed: 75,
      damage: 29,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_XiSilanus.BP_Gun_XiSilanus_C'",
      repair_per_hp: 8.5699996948242188,
      level_required: 0,
      total_hp: 350,
      cost_price: 75000,
      money_type: 0,
      static_mesh: "None",
      reference: 118,
      item_name: "Xi Silanus",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Xi_Silanus.T_Icon_Xi_Silanus'",
      description: ""
    },
    {
      name: "119",
      firing_sound: "None",
      accuracy: 50,
      speed: 65,
      damage: 38,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_SilverStorm2.BP_Gun_SilverStorm2_C'",
      repair_per_hp: 6.880000114440918,
      level_required: 0,
      total_hp: 400,
      cost_price: 100000,
      money_type: 0,
      static_mesh: "None",
      reference: 119,
      item_name: "Silver Storm ll",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_Silver_Storm_ll.T_Icon_Silver_Storm_ll'",
      description: ""
    },
    {
      name: "120",
      firing_sound: "None",
      accuracy: 45,
      speed: 75,
      damage: 35,
      type: 0,
      blueprint: "BlueprintGeneratedClass'/Game/Blueprints/Cockpit/Fire/GunTypes/BP_Gun_XenSilanus.BP_Gun_XenSilanus_C'",
      repair_per_hp: 7,
      level_required: 0,
      total_hp: 450,
      cost_price: 125000,
      money_type: 0,
      static_mesh: "None",
      reference: 120,
      item_name: "XenSilanus",
      icon: "Texture2D'/Game/Assets/Hangar/GunsIcons/T_Icon_XenSilanus.T_Icon_XenSilanus'",
      description: ""
    }
  ];

  await prisma.guns.createMany({
    data: guns,
  });

  console.log('Guns seeded successfully');
}